Who knew chrome was such a pain in the ass, I'm going to just start using dot

diff --git a/.github/workflows/doc.yml b/.github/workflows/doc.yml
--- a/.github/workflows/doc.yml
+++ b/.github/workflows/doc.yml
@@ -83,10 +83,10 @@ jobs:
         run: |
             pip install --upgrade pip
             pip install -r scripts/doc-requirements.txt
-            npm install -g @mermaid-js/mermaid-cli
-            which -a mmdc | echo "Not found"
+            npm install @mermaid-js/mermaid-cli
+            which -a mmdc || echo "Not found"
             npx puppeteer browsers install
-            which -a mmdc | echo "Not found"
+            which -a mmdc || echo "Not found"
       - name: Configure celeritas
         run: |
           # NOTE: tags have issues, see https://github.com/actions/checkout/issues/2041
